### ISSUE TITLE
please tell me you can help me i need this bot man lol 

### ISSUE THREAD

**Issue by hazed59** [rysiuwroc/AlbionBot#1]
Error: Cannot find module '../../functions/db/correlation-user-player-discoguild-get'
Require stack:
- /home/runner/AlbionBot/libs/commands/main/register.js
- /home/runner/AlbionBot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/AlbionBot/libs/commands/main/register.js:6:44)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/AlbionBot/libs/commands/main/register.js',
    '/home/runner/AlbionBot/index.js'

**Comment by rysiuwroc** [comment]
Bot is in Work in Progress stage.
Unfortunately it is not currently possible to get it running locally.

**Comment by hazed59** [comment]
Man U don’t know how bad I really need this bot lol like I’ve been searching for one like it forever when do u think it will be finished?
